=== AlexFigas/USV/docs/Programas/TurnOut-V11/data/settings.dtd
<!ELEMENT Settings        (Wifi, GlobalMotion, Expanders, Servos, Crossings) >

<!ELEMENT Wifi            (ssid, password, address, gateway, network) >
<!ELEMENT ssid            (#PCDATA) >
<!ELEMENT password        (#PCDATA) >
<!ELEMENT address         (#PCDATA) >
<!ELEMENT gateway         (#PCDATA) >
<!ELEMENT network         (#PCDATA) >
<!ATTLIST Wifi            apMode ( 0 | 1 ) "1" >

<!ELEMENT GlobalMotion    (Range) >

<!ELEMENT Range           (min, value, max) >
<!ELEMENT min             (#PCDATA) >
<!ELEMENT value           (#PCDATA) >
<!ELEMENT max             (#PCDATA) >
<!ATTLIST Range           units CDATA #REQUIRED >

<!ELEMENT Expanders       (ExpandersPWM, ExpandersIO) >

<!ELEMENT ExpandersPWM    (ExpanderPWM)* >

<!ELEMENT ExpanderPWM     EMPTY >
<!ATTLIST ExpanderPWM     address CDATA #REQUIRED
                          desc CDATA #IMPLIED >

<!ELEMENT ExpandersIO     (ExpanderIO)* >

<!ELEMENT ExpanderIO      EMPTY >
<!ATTLIST ExpanderIO      address CDATA #REQUIRED
                          pinIRQ CDATA #REQUIRED
                          desc CDATA #IMPLIED >

<!ELEMENT Servos          (Servo)* >
<!ELEMENT Servo           (Range, Range) >
<!ATTLIST Servo           name CDATA #REQUIRED
                          expander CDATA #REQUIRED
                          index CDATA #REQUIRED
                          smooth ( 0 | 1 ) "1"
                          desc CDATA #REQUIRED >

<!ELEMENT Crossings       (Crossing)* >

<!ELEMENT Crossing        (Sensors, Fences, Sound, Range, Range) >
<!ATTLIST Crossing        name CDATA #REQUIRED
                          desc CDATA #IMPLIED >

<!ELEMENT Sensors         (Enter, Leave, Light) >

<!ELEMENT Enter           (PortIn)* >

<!ELEMENT PortIn          EMPTY >
<!ATTLIST PortIn          expander CDATA #REQUIRED
                          mask CDATA #REQUIRED >

<!ELEMENT Leave           (PortIn)* >

<!ELEMENT Light           (PortOut)* >

<!ELEMENT PortOut         EMPTY >
<!ATTLIST PortOut         servo CDATA #REQUIRED >

<!ELEMENT Fences          (Fence)* >

<!ELEMENT Fence           EMPTY >
<!ATTLIST Fence           servo CDATA #REQUIRED >

<!ELEMENT Sound           EMPTY >
<!ATTLIST Sound           pinDAC CDATA #REQUIRED
                          timerDAC CDATA #REQUIRED
                          soundFileName CDATA #REQUIRED >

=== AlexFigas/USV/docs/Programas/TurnOut-V11/data/settings.xml
<?xml version='1.0' encoding='UTF-8' standalone='no' ?>
<!DOCTYPE Settings SYSTEM 'settings.dtd'>

<Settings>
	<Wifi apMode="1">
		<ssid>Tires-Trains</ssid>
		<password>s@gredo</password>
		<address>192.168.5.5</address>
		<gateway>192.168.5.1</gateway>
		<network>255.255.255.0</network>
	</Wifi>

	<GlobalMotion>
		<Range units="ms">
			<min>25</min>
			<value>50</value>
			<max>500</max>
		</Range>
	</GlobalMotion>
	
	<Expanders>
		<ExpandersPWM>
			<ExpanderPWM address="0x40" desc="PWM Expander #1" />
		</ExpandersPWM>
		
		<ExpandersIO>
			<ExpanderIO address="0x20" pinIRQ="12" desc="IO Expander #1" />
		</ExpandersIO>
	</Expanders>
	
	<Servos>
		<Servo name="Passagem nível vila" expander="0" index="0" smooth="1" desc="Entrada norte" >
			<Range units="ms">
				<min>100</min>
				<value>140</value>
				<max>500</max>
			</Range>
			<Range units="ms">
				<min>100</min>
				<value>340</value>
				<max>500</max>
			</Range>
		</Servo>
		
		<Servo name="Passagem nível vila" expander="0" index="1" smooth="1" desc="Entrada sul" >
			<Range units="ms">
				<min>100</min>
				<value>140</value>
				<max>500</max>
			</Range>
			<Range units="ms">
				<min>100</min>
				<value>340</value>
				<max>500</max>
			</Range>
		</Servo>
		
		<Servo name="Passagem nível vila" expander="0" index="2" smooth="0" desc="Luzes" >
			<Range units="ms">
				<min>0</min>
				<value>0</value>
				<max>4095</max>
			</Range>
			<Range units="ms">
				<min>0</min>
				<value>4095</value>
				<max>4095</max>
			</Range>
		</Servo>

		<Servo name="Ponte Velha" expander="0" index="3" smooth="1" desc="" >
			<Range units="ms">
				<min>100</min>
				<value>110</value>
				<max>500</max>
			</Range>
			<Range units="ms">
				<min>100</min>
				<value>350</value>
				<max>500</max>
			</Range>
		</Servo>
		
		<Servo name="Tunel" expander="0" index="4" smooth="1" desc="" >
			<Range units="ms">
				<min>100</min>
				<value>110</value>
				<max>500</max>
			</Range>
			<Range units="ms">
				<min>100</min>
				<value>350</value>
				<max>500</max>
			</Range>
		</Servo>
	</Servos>
	
	<Crossings>
		<Crossing name="Passagem nível vila" desc="Com cancela">
			<Sensors>
				<Enter>
					<PortIn expander="0" mask="0x01" />
				</Enter>
				<Leave>
					<PortIn expander="0" mask="0x02" />
				</Leave>
				<Light>
					<PortOut servo="2" />
				</Light>
			</Sensors>
			
			<Fences>
				<Fence servo="0" />
				<Fence servo="1" />
			</Fences>
			
			<Sound pinDAC="25" timerDAC="0" soundFileName="/ring.dat" />
			
			<Range units="%">
				<min>0</min>
				<value>20</value>
				<max>100</max>
			</Range>
			<Range units="%">
				<min>0</min>
				<value>80</value>
				<max>100</max>
			</Range>
		</Crossing>
	</Crossings>
</Settings>
